import { existsSync } from 'node:fs';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import yaml from 'js-yaml';

// ANSI color codes
const GREEN = '\x1b[32m';
const YELLOW = '\x1b[33m';
const RESET = '\x1b[0m';

export interface InitCommandOptions {
  preset?: string;
  force?: boolean;
}

interface DetectedStack {
  labels: string[];
  modules: string[];
}

async function detectProjectStack(cwd: string): Promise<DetectedStack> {
  const labels: string[] = [];
  const modules: string[] = ['base', 'korean-conventions'];

  // Check for package.json
  const packageJsonPath = join(cwd, 'package.json');
  if (existsSync(packageJsonPath)) {
    labels.push('Node.js');
    try {
      const raw = await readFile(packageJsonPath, 'utf-8');
      const pkg = JSON.parse(raw) as { dependencies?: Record<string, string>; devDependencies?: Record<string, string> };
      const allDeps = { ...pkg.dependencies, ...pkg.devDependencies };
      const depKeys = Object.keys(allDeps);

      if (depKeys.some((k) => k === 'next')) {
        labels.push('Next.js');
        if (!modules.includes('nextjs-project')) {
          // No built-in module yet, but mark it
        }
      }
      if (depKeys.some((k) => k === 'react' || k === 'react-dom')) {
        labels.push('React');
      }
      if (depKeys.some((k) => k === 'express')) {
        labels.push('Express');
      }
    } catch {
      // ignore parse errors
    }
  }

  // Check for Python
  if (existsSync(join(cwd, 'requirements.txt')) || existsSync(join(cwd, 'pyproject.toml'))) {
    labels.push('Python');
  }

  // Check for Docker
  if (existsSync(join(cwd, 'Dockerfile'))) {
    labels.push('Docker');
    if (!modules.includes('docker-project')) {
      modules.push('docker-project');
    }
  }

  if (existsSync(join(cwd, 'docker-compose.yml')) || existsSync(join(cwd, 'docker-compose.yaml'))) {
    if (!labels.includes('Docker')) labels.push('Docker');
    labels.push('Docker Compose');
    if (!modules.includes('docker-project')) {
      modules.push('docker-project');
    }
  }

  if (labels.length === 0) {
    labels.push('Unknown');
  }

  return { labels, modules };
}

function buildConfigYaml(modules: string[], existingClaudeMd: boolean, preset?: string): string {
  const moduleEntries = modules.map((m) => `  - name: ${m}`).join('\n');
  const customBlock = existingClaudeMd
    ? `custom:\n  - id: existing-claude-md\n    section: "## Preserved"\n    content: |\n      # (Paste your existing CLAUDE.md content here)\n`
    : 'custom: []';
  const presetLine = preset ? `preset: ${preset}\n` : '';

  return [
    `version: '1'`,
    presetLine.trim() ? presetLine.trim() : null,
    `modules:`,
    moduleEntries,
    customBlock,
  ]
    .filter((line) => line !== null)
    .join('\n') + '\n';
}

async function runBuild(cwd: string, verbose: boolean): Promise<{ modules: number; lines: number }> {
  // Read config and run the build pipeline
  const configPath = join(cwd, 'harness.config.yaml');
  let moduleCount = 0;
  try {
    const raw = await readFile(configPath, 'utf-8');
    const parsed = yaml.load(raw) as { modules?: unknown[] };
    moduleCount = Array.isArray(parsed?.modules) ? parsed.modules.length : 0;
  } catch {
    // ignore
  }

  try {
    const { runPipeline } = await import('../pipeline/index.js');
    const { HarnessConfigSchema } = await import('../types/index.js');
    const raw = await readFile(configPath, 'utf-8');
    const rawConfig = yaml.load(raw);
    const parseResult = HarnessConfigSchema.safeParse(rawConfig);
    if (parseResult.success) {
      await runPipeline(parseResult.data, { verbose, outputDir: cwd });
    }
    return { modules: moduleCount, lines: 4 };
  } catch {
    // Fallback: write minimal placeholder files
    const claudeMdPath = join(cwd, 'CLAUDE.md');
    const content = `# CLAUDE.md\n\n<!-- Generated by harness-kit -->\n<!-- Run 'harness-kit build' to regenerate -->\n`;
    await writeFile(claudeMdPath, content, 'utf-8');

    const settingsDir = join(cwd, '.claude');
    await mkdir(settingsDir, { recursive: true });
    const settingsPath = join(settingsDir, 'settings.json');
    const settings = { hooks: {}, mcpServers: {} };
    await writeFile(settingsPath, JSON.stringify(settings, null, 2) + '\n', 'utf-8');

    const harnessDir = join(cwd, '.harness');
    await mkdir(harnessDir, { recursive: true });
    const manifestPath = join(harnessDir, '.build-manifest.json');
    const manifest = {
      version: '1',
      built_at: new Date().toISOString(),
      config_hash: 'placeholder',
      modules: [],
      output_hash: 'placeholder',
    };
    await writeFile(manifestPath, JSON.stringify(manifest, null, 2) + '\n', 'utf-8');

    return { modules: moduleCount, lines: 4 };
  }
}

export async function initCommand(options: InitCommandOptions): Promise<void> {
  const cwd = process.cwd();
  const configPath = join(cwd, 'harness.config.yaml');

  // Check if config already exists and --force not set
  if (existsSync(configPath) && !options.force) {
    console.error(`Error: harness.config.yaml already exists. Use --force to overwrite.`);
    process.exit(1);
  }

  // Detect project stack
  const { labels, modules } = await detectProjectStack(cwd);

  // Apply preset if given
  if (options.preset) {
    // Preset support is a future feature; note it
    console.log(`${YELLOW}⚠${RESET}  Preset '${options.preset}' not yet available — using detected modules`);
  }

  console.log(`${GREEN}✓${RESET} Detected: ${labels.join(' + ')}`);
  console.log(`${GREEN}✓${RESET} Recommended modules: ${modules.join(', ')}`);

  // Check for existing CLAUDE.md
  const claudeMdPath = join(cwd, 'CLAUDE.md');
  const hasExistingClaudeMd = existsSync(claudeMdPath);
  if (hasExistingClaudeMd) {
    console.log(`${YELLOW}⚠${RESET}  Existing CLAUDE.md detected — content preserved in custom block`);
  }

  // Generate harness.config.yaml
  const configContent = buildConfigYaml(modules, hasExistingClaudeMd, options.preset);
  await writeFile(configPath, configContent, 'utf-8');
  console.log(`${GREEN}✓${RESET} Generated: harness.config.yaml`);

  // Create .harness/modules directory
  const localModulesDir = join(cwd, '.harness', 'modules');
  await mkdir(localModulesDir, { recursive: true });

  // Run build immediately
  const buildResult = await runBuild(cwd, false);
  const settingsPath = join(cwd, '.claude', 'settings.json');
  const hooksCount = 0;
  const mcpCount = 0;
  const settingsInfo = existsSync(settingsPath)
    ? `(${hooksCount} hooks, ${mcpCount} mcp)`
    : '(not created)';

  console.log(`${GREEN}✓${RESET} Build complete:`);
  console.log(`  - CLAUDE.md (${buildResult.modules} modules, ${buildResult.lines} lines)`);
  console.log(`  - .claude/settings.json ${settingsInfo}`);
}
